### PR TITLE
add generally accepted guidelines to date

### PR DESCRIPTION
**Pull request by wsor4035**
unless im missing this somewhere else. feel free to suggest better wording

### CODE REVIEW

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by OgelGames** [comment]
Jumping to a PR a bit too early, I was talking about more than just those two points I mentioned.

Also, that section is about project acceptance, not about contributing/maintenance.

**Comment by wsor4035** [comment]
> Jumping to a PR a bit too early, I was talking about more than just those two points I mentioned.

adding core things, you are free to bring up your more stuff in a future pr. I'm just adding existing stuff

**Comment by luk3yx** [comment]
I suggest this:

> \<ogelgames\> a PR should be made for anything more than a typo, but especially when it's adding a hacky bugfix

Perhaps with an exception for maintainers of the mod, CI updates, etc

**Comment by wsor4035** [comment]
@luk3yx 
`PR's should be approved by one mt-mods member (not yourself) outside of simple bugfixes, trival changes, etc` replace with
`PR's should be created and approved by one mt-mods member (not yourself) unless they are (simple bugfixes, trival changes, etc)`
better/counter suggestion?

**Comment by luk3yx** [comment]
> @luk3yx `PR's should be approved by one mt-mods member (not yourself) outside of simple bugfixes, trival changes, etc` replace with `PR's should be created and approved by one mt-mods member (not yourself) unless they are (simple bugfixes, trival changes, etc)` better/counter suggestion?

That sounds fine, I'm not really sure how to define "simple bugfixes" or "trivial changes" though (and I don't know whether they still need a PR even if you don't need to get approval for it).

**Comment by wsor4035** [comment]
> (and I don't know whether they still need a PR even if you don't need to get approval for it)

suggestion to clarify

```
* PR's should be created for any changes and approved by one mt-mods member (not yourself)
* the following are exempted from the above and can be directly commited: simple bugfixes, trival changes, etc
```

**Review by BuckarooBanzay — APPROVED** [review]

**Review by Niklp09 — APPROVED** [review]
no big deal, those rules already existed unofficially before

**Pull request merged**
